Frontend initialized
HimanShu0923/Codeforces-Author-Analyzer pull request #9
Opened 2023-07-16 08:33 UTC by jatin142002

The initial setup of the frontend is done.

2023-07-16 10:03 UTC, Aksh-Bansal-dev requested changes
We will not use `ejs`, instead we will use `html`.

Also, test this in local.

2023-07-16 10:03 UTC, Aksh-Bansal-dev commented on frontend/views/home.ejs
> +    <div id="topicsDict"><%=JSON.stringify(topicsDict)%></div>
remove ejs code

2023-07-16 10:03 UTC, Aksh-Bansal-dev commented on frontend/js/home.js
> +      })
Refactor code to remove duplication

2023-07-16 10:03 UTC, Aksh-Bansal-dev commented on frontend/js/home.js
> +      .then((json) => {
Make a global dummy url for lambda and take the schema as told earlier.

2023-07-16 10:03 UTC, Aksh-Bansal-dev commented on frontend/js/home.js
> +      .then((json) => {
POST `<lambda_endpoint>`
request:
```
body: {
  authorId: string
}
```
response:

```

{
  "<tag_name>": []Problem 
}
```
```
Problem {
  name string, 
  rating int,
  problem_url string,
}
```

2023-07-17 01:36 UTC, HimanShu0923 approved these changes

2023-07-17 01:36 UTC, merged